//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.01 at 03:41:25 AM MSK 
//


package com.aleksandr0412.spring_ws.bookstore;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="book" type="{http://aleksandr0412.com/spring-ws/bookstore}book"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "book"
})
@XmlRootElement(name = "getBookByIdResponse")
public class GetBookByIdResponse {

    @XmlElement(required = true)
    protected Book book;

    /**
     * Gets the value of the book property.
     *
     * @return possible object is
     * {@link Book }
     */
    public Book getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     *
     * @param value allowed object is
     *              {@link Book }
     */
    public void setBook(Book value) {
        this.book = value;
    }

}
