//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.01 at 03:41:25 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://aleksandr0412.com/spring-ws/bookstore", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.aleksandr0412.spring_ws.bookstore;
